version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nodeCmdApp/Dockerfile
    command: gulp
    volumes:
      - ./cmdApp:/code
    ports:
      - "8000:8000"
      - "5858:5858"
      - "4000:4000"
      - "8080:8080"
      - "5000:5000"
      - "3001:3001"
      - "9229:9229"  
#  note-app:
#  	build:
#      context: .
#      dockerfile: ./docker/nodeCmdApp
#    command: gulp
#    volumes:
#      - ./app:/code
#    ports:
#      - "8080:8080"
#      - "6868:6868"
